#!/usr/bin/env ruby
require "brainfuck"
Brainfuck::Interpreter.new(File.read(ARGV[0]).gsub(/\s+/,''))
#"++++++++++[>+++++++>++++++++++>+++>+<<<<-]>++.>+.+++++++..+++.>++.<<+++++++++++++++.>.+++.------.--------.>+.>."
